version: "3"
services: 
    app:
        build:
            context: ./
            dockerfile: Dockerfile.development
        container_name: s-docker
        tty: true
        volumes: 
            - .:/app
        ports: 
            - 8080:8080